INSERT INTO base_item_entity (name,
                              description,
                              item_type,
                              slot_type,
                              base_rizz,
                              base_strength,
                              base_agility,
                              base_endurance,
                              base_luck,
                              base_price,
                              image_path)
VALUES ('Zimowa czapka', 'Ma znajomy zapach.', 'EQUIPMENT', 'HEAD', 5, 2, 0, 7, 5, 40, 'item-winter-hat.png'),
       ('Słomiany kapelusz', '', 'EQUIPMENT', 'HEAD', 3, 0, 10, 6, 1, 40, 'item-straw-hat.png'),
       ('Różowe okulary', '', 'EQUIPMENT', 'HEAD', 7, 3, 3, 6, 8, 52, 'item-pink-sunglasses.png'),
       ('Czapka rolnika', '50% rabatu na tygodnik rolniczy', 'EQUIPMENT', 'HEAD', 4, 3, 0, 9, 0, 35,
        'item-farmer-cap.png'),
       ('Pomarańczowe okulary', 'Drobnym druczkiem ma napisane: "Made in PRL".', 'EQUIPMENT', 'HEAD', 5, 0, 4, 5, 3, 35,
        'item-orange-sunglasses.png'),
       ('Słuchawki gamingowe', '', 'EQUIPMENT', 'HEAD', 7, 0, 6, 4, 2, 42, 'item-gaming-headset.png'),
       ('Czerwona kominiara', '', 'EQUIPMENT', 'HEAD', 2, 6, 0, 10, 0, 40, 'item-balaclava.png'),
       ('Kask budowlańca', 'Budowlaniec go raczej nie nosił, bo wygląda jak nowy.', 'EQUIPMENT', 'HEAD', 1, 6, 0, 15, 0,
        48, 'item-builder-helmet.png'),
       ('Czapka bucket', '', 'EQUIPMENT', 'HEAD', 4, 0, 4, 8, 2, 35, 'item-bucket-hat.png'),
       ('Okulary z wąsami', '+1000 do nierozpoznawalności', 'EQUIPMENT', 'HEAD', 10, 0, 0, 7, 10, 40,
        'item-glasses-with-moustache.png'),

       ('Karta do akademika', 'Na odwrocie ma napisane "Pokój 509/1".', 'EQUIPMENT', 'NECK', 3, 3, 0, 8, 0, 35,
        'item-dormitory-card.png'),
       ('Szalik Gajelonii', 'Lepiej nie pojawiać się z nim w złym mieście.', 'EQUIPMENT', 'NECK', 2, 7, 3, 4, 0, 40,
        'item-sport-scarf.png'),
       ('Wisiorek z krucyfiksem', '', 'EQUIPMENT', 'NECK', 3, 3, 3, 3, 1, 40, 'item-crucifix-necklace.png'),
       ('Czerwone korale', '', 'EQUIPMENT', 'NECK', 4, 4, 4, 4, 2, 44, 'item-red-corals.png'),
       ('Złoty łańcuch', 'Podobno oryginalnie kosztował 40 koła.', 'EQUIPMENT', 'NECK', 7, 5, 0, 3, 0, 40,
        'item-golden-chain.png'),
       ('Nieśmiertelnik', 'Na wypadek gdybyś zaliczył/a zgona.', 'EQUIPMENT', 'NECK', 3, 3, 0, 13, 3, 55,
        'item-dog-tag.png'),
       ('Choker z kolcami', '', 'EQUIPMENT', 'NECK', 8, 1, 1, 3, 0, 50, 'item-choker.png'),
       ('Apaszka', '', 'EQUIPMENT', 'NECK', 4, 0, 6, 2, 2, 45, 'item-scarf.png'),
       ('Krawat', '', 'EQUIPMENT', 'NECK', 5, 3, 2, 3, 0, 45, 'item-tie.png'),
       ('Czerwona muszka', 'Po założeniu masz ochotę na herbatę z olbrzymią ilością cukru.', 'EQUIPMENT', 'NECK', 7, 0,
        3, 6, 3, 52, 'item-bowtie.png'),

       ('Biała marynarka', '', 'EQUIPMENT', 'UPPER_BODY', 7, 3, 3, 12, 1, 48, 'item-white-suit.png'),
       ('Hawajska koszula', '', 'EQUIPMENT', 'UPPER_BODY', 6, 3, 5, 8, 1, 45, 'item-hawaiian-shirt.png'),
       ('Czarna suknia', '', 'EQUIPMENT', 'UPPER_BODY', 8, 0, 5, 10, 1, 44, 'item-black-dress.png'),
       ('Patriotyczna bluza', '', 'EQUIPMENT', 'UPPER_BODY', 0, 11, 6, 15, 0, 52, 'item-patriotic-hoodie.png'),
       ('Fartuch kuchenny', 'Przez żółądek do serca.', 'EQUIPMENT', 'UPPER_BODY', 8, 4, 8, 7, 4, 50,
        'item-kitchen-apron.png'),
       ('Biała bluzka', '', 'EQUIPMENT', 'UPPER_BODY', 4, 1, 5, 12, 0, 45, 'item-white-blouse.png'),
       ('Skórzana kurtka', '', 'EQUIPMENT', 'UPPER_BODY', 7, 8, 0, 16, 1, 50, 'item-leather-jacket.png'),
       ('Długi płaszcz', 'Emanuje zapachem szlugów.', 'EQUIPMENT', 'UPPER_BODY', 4, 10, 5, 15, 2, 65,
        'item-long-jacket.png'),
       ('Żonobijka', '', 'EQUIPMENT', 'UPPER_BODY', 7, 15, 3, 7, 0, 55, 'item-sleeveless-shirt.png'),
       ('Sztywna koszulka', '', 'EQUIPMENT', 'UPPER_BODY', 5, 12, 5, 12, 0, 40, 'item-rigid-tshirt.png'),

       ('Stare Jeansy', '', 'EQUIPMENT', 'LOWER_BODY', 3, 0, 2, 10, 0, 38, 'item-old-jeans.png'),
       ('Spodnie od garniaka', '', 'EQUIPMENT', 'LOWER_BODY', 6, 3, 4, 7, 1, 45, 'item-white-suit-pants.png'),
       ('Czarna spódniczka', '', 'EQUIPMENT', 'LOWER_BODY', 9, 0, 8, 8, 1, 47, 'item-black-skirt.png'),
       ('Spodnie moro', '', 'EQUIPMENT', 'LOWER_BODY', 2, 7, 3, 12, 0, 45, 'item-military-pants.png'),
       ('Fioletowe rajstopy', '', 'EQUIPMENT', 'LOWER_BODY', 5, 0, 7, 7, 1, 41, 'item-purple-tights.png'),
       ('Kąpielówki', '', 'EQUIPMENT', 'LOWER_BODY', 4, 2, 9, 7, 3, 44, 'item-swimming-trunks.png'),
       ('Ogrodniczki', '', 'EQUIPMENT', 'LOWER_BODY', 4, 5, 1, 11, 0, 40, 'item-dungarees.png'),
       ('Koszykarskie spodenki', '', 'EQUIPMENT', 'LOWER_BODY', 3, 4, 12, 9, 3, 52, 'item-basketball-shorts.png'),
       ('Spódnica baletnicy', '', 'EQUIPMENT', 'LOWER_BODY', 7, 3, 15, 4, 0, 48, 'item-ballerina-skirt.png'),
       ('Dresy Abibasa', '', 'EQUIPMENT', 'LOWER_BODY', 3, 6, 5, 11, 0, 50, 'item-sweatpants.png'),

       ('Wysokie buty', '+10 cm do wzrostu.', 'EQUIPMENT', 'FEET', 6, 6, 0, 9, 0, 44, 'item-high-soled-shoes.png'),
       ('Kalosze', '', 'EQUIPMENT', 'FEET', 2, 8, 1, 11, 0, 43, 'item-rain-boots.png'),
       ('Stare trampki', 'Powinny jeszcze wytrzymać z 10 lat.', 'EQUIPMENT', 'FEET', 1, 5, 5, 6, 0, 32,
        'item-old-sneakers.png'),
       ('Crocsy', '', 'EQUIPMENT', 'FEET', 3, 8, 5, 10, 0, 50, 'item-crocs.png'),
       ('Sztyblety', 'Rozlazłe, jakby chodził w nich jakiś steryd.', 'EQUIPMENT', 'FEET', 5, 8, 1, 11, 0, 46,
        'item-chelsea-boots.png'),
       ('Czarne szpilki', '', 'EQUIPMENT', 'FEET', 7, 6, 0, 6, 1, 40, 'item-black-heels.png'),
       ('Sandały', 'Ze skarpetami w pakiecie stanowią zabójcze połączenie.', 'EQUIPMENT', 'FEET', 8, 3, 8, 5, 0, 47,
        'item-sandals.png'),
       ('Łyżwy', '', 'EQUIPMENT', 'FEET', 3, 3, 10, 9, 1, 55, 'item-skates.png'),
       ('Japonki', '', 'EQUIPMENT', 'FEET', 4, 1, 8, 5, 5, 43, 'item-flip-flops.png'),

       ('Złota branzoletka', '', 'EQUIPMENT', 'WRIST', 4, 5, 0, 3, 2, 40, 'item-golden-bracelet.png'),
       ('Sikor', '', 'EQUIPMENT', 'WRIST', 7, 0, 0, 1, 3, 40, 'item-leather-watch.png'),
       ('Branzoletka przyjaźni', '', 'EQUIPMENT', 'WRIST', 4, 6, 0, 5, 1, 45, 'item-friendship-bracelet.png'),
       ('Frotkowa opaska', '+10 do skręcania.', 'EQUIPMENT', 'WRIST', 4, 2, 0, 6, 7, 67, 'item-chill-wristband.png'),
       ('Smartwatch', '', 'EQUIPMENT', 'WRIST', 3, 3, 3, 3, 3, 50, 'item-smartwatch.png'),
       ('Opaska policyjna', 'Może zdążysz zrobić pare questów zanim po ciebie przyjadą.', 'EQUIPMENT', 'WRIST', 6, 6, 3,
        0, 1, 52, 'item-supervision-armband.png'),
       ('Zegarek szwagra', '', 'EQUIPMENT', 'WRIST', 8, 4, 0, 1, 0, 43, 'item-szwagier-watch.png'),
       ('Srebrna branzoleta', '', 'EQUIPMENT', 'WRIST', 5, 3, 1, 1, 0, 40, 'item-silver-bracelet.png'),
       ('Opaska odblaskowa', '', 'EQUIPMENT', 'WRIST', 3, 0, 3, 2, 0, 30, 'item-reflective-band.png'),
       ('Opaska z juwenaliów', 'Za rok będzie będzie 5 razy droższa, za te same statystyki.', 'EQUIPMENT', 'WRIST', 4,
        1, 4, 4, 0, 80, 'item-juwenalia-wristband.png'),
       ('Opaska fluorescencyjna', '', 'EQUIPMENT', 'WRIST', 5, 0, 7, 0, 3, 35, 'item-fluorescent-wristband.png'),
       ('Cukierkowy zegarek', 'Pilnuj, żeby nikt ci go nie zjadł.', 'EQUIPMENT', 'WRIST', 7, 4, 0, 0, 5, 45,
        'item-candy-watch.png'),

       ('Zapalniczka', 'Ledwo działa, ale fajnie wygląda.', 'EQUIPMENT', 'EMBLEM', 6, 4, 3, 0, 3, 45,
        'item-lighter.png'),
       ('Paczka szlugów', 'Z ruską banderolą.', 'EQUIPMENT', 'EMBLEM', 9, 6, 0, 0, 4, 50, 'item-cigarettes.png'),
       ('Tani vape', 'Skasowany jakiemuś uczniowi podstawówki.', 'EQUIPMENT', 'EMBLEM', 5, 6, 0, 0, 2, 40,
        'item-cheap-vape.png'),
       ('Pluszak Babulu', '', 'EQUIPMENT', 'EMBLEM', 6, 3, 1, 0, 5, 55, 'item-babulu-plush.png'),
       ('Dezodorant', 'Idealny na cygański prysznic.', 'EQUIPMENT', 'EMBLEM', 7, 7, 3, 1, 0, 48, 'item-deodorant.png'),
       ('Pudełko snusów', '', 'EQUIPMENT', 'EMBLEM', 6, 5, 1, 1, 2, 48, 'item-snus.png'),
       ('Różowa torebka', '', 'EQUIPMENT', 'EMBLEM', 5, 8, 2, 2, 5, 52, 'item-pink-bag.png'),
       ('Karty tarota', '', 'EQUIPMENT', 'EMBLEM', 4, 4, 4, 4, 12, 65, 'item-tarot.png'),
       ('Butelka zwrotna', 'Jeszcze takie trzy i będzie kolejne piwo.', 'EQUIPMENT', 'EMBLEM', 5, 8, 0, 2, 3, 51,
        'item-returnable-bottle.png'),
       ('Alkomat', '', 'EQUIPMENT', 'EMBLEM', 4, 4, 7, 0, 5, 40, 'item-alkomat.png'),
       ('Konsola', '', 'EQUIPMENT', 'EMBLEM', 5, 7, 0, 0, 10, 55, 'item-console.png'),


       ('Numerek do szatni 03', 'Wymień go u szatniarza.', 'ITEM_TOKEN', 'NONE', 0, 0, 0, 0, 1, 0, 'item-token-03.png'),
       ('Numerek do szatni 12', 'Wymień go u szatniarza.', 'ITEM_TOKEN', 'NONE', 0, 0, 0, 0, 1, 0, 'item-token-12.png'),
       ('Numerek do szatni 13', 'Wymień go u szatniarza.', 'ITEM_TOKEN', 'NONE', 0, 0, 0, 0, 1, 0, 'item-token-13.png'),
       ('Numerek do szatni 21', 'Wymień go u szatniarza.', 'ITEM_TOKEN', 'NONE', 0, 0, 0, 0, 1, 0, 'item-token-21.png'),
       ('Numerek do szatni 34', 'Wymień go u szatniarza.', 'ITEM_TOKEN', 'NONE', 0, 0, 0, 0, 1, 0, 'item-token-34.png'),
       ('Numerek do szatni 55', 'Wymień go u szatniarza.', 'ITEM_TOKEN', 'NONE', 0, 0, 0, 0, 1, 0, 'item-token-55.png'),
       ('Numerek do szatni 58', 'Wymień go u szatniarza.', 'ITEM_TOKEN', 'NONE', 0, 0, 0, 0, 1, 0, 'item-token-58.png'),
       ('Numerek do szatni 67', 'Wymień go u szatniarza.', 'ITEM_TOKEN', 'NONE', 0, 0, 0, 0, 7, 0, 'item-token-67.png'),
       ('Numerek do szatni 77', 'Wymień go u szatniarza.', 'ITEM_TOKEN', 'NONE', 0, 0, 0, 0, 1, 0, 'item-token-77.png'),
       ('Numerek do szatni 89', 'Wymień go u szatniarza.', 'ITEM_TOKEN', 'NONE', 0, 0, 0, 0, 1, 0, 'item-token-89.png'),
       ('Numerek do szatni 99', 'Wymień go u szatniarza.', 'ITEM_TOKEN', 'NONE', 0, 0, 0, 0, 1, 0, 'item-token-99.png'),
       ('Numerek do szatni 420', 'Wymień go u szatniarza.', 'ITEM_TOKEN', 'NONE', 0, 0, 0, 0, 7, 0,
        'item-token-420.png');

INSERT INTO opponent_entity (name,
                             base_rizz,
                             base_strength,
                             base_agility,
                             base_endurance,
                             base_luck,
                             image_path)
VALUES ('Gruba', 3, 6, 1, 47, 1, 'opponent_gruba.png'),
       ('Dresiarz', 6, 10, 5, 40, 2, 'opponent_dresiarz.png'),
       ('Hiszpan', 11, 8, 6, 33, 2, 'opponent_hiszpan.png'),
       ('Ochroniarz', 7, 12, 5, 52, 4, 'opponent_ochroniarz.png'),
       ('Blondyna', 15, 7, 7, 30, 3, 'opponent_blondyna.png'),
       ('Menel', 4, 6, 3, 35, 10, 'opponent_menel.png'),
       ('DJ', 12, 9, 4, 45, 4, 'opponent_dj.png'),
       ('Barmanka', 10, 8, 6, 37, 5, 'opponent_bartender.png'),

       ('Andrzej Miękkowski', 50, 0, 5, 500, 5, 'boss_andrzej.png'),
       ('Borys Piotrenko', 0, 80, 10, 1000, 30, 'boss_piotrenko.png');



INSERT INTO quest_entity (title,
                          description,
                          quest_tier,
                          quest_type,
                          opponent_id,
                          image_path)
VALUES ('Rizzowanie grubej', 'Wydajesz się być zdesperowany. Spróbuj może zrizzować grubą.', 'EASY', 'RIZZ_FIGHT', 1,
        'rizz_quest1.png'),
       ('Wyjaśnij Hiszpana', 'Wkurza mnie już ten Erazmus, pokaż mu gdzie jego miejsce!', 'EASY', 'STRENGTH_FIGHT', 3,
        'fight_quest6.png'),
       ('Pozbądź się menela', 'Jakiś menel wtargnął nam do lokalu. Pozbędziesz się go?', 'EASY', 'STRENGTH_FIGHT', 6,
        'fight_quest7.png'),
       ('Ogarnij DJ-a', 'Przemów do rozsądku temu DJ-owi, żeby puścił coś normalnego.', 'EASY', 'STRENGTH_FIGHT', 7,
        'fight_quest8.png'),
       ('Samotny menel', 'Szkoda mi się zrobiło tego menela, weź idź z nim zatańcz czy coś.', 'EASY', 'RIZZ_FIGHT', 6,
        'rizz_quest7.png'),
       ('Poderwij dresiarza', 'Widzisz tego dresa na parkiecie? Założę się że go nie poderwiesz!', 'EASY', 'RIZZ_FIGHT',
        2, 'rizz_quest4.png'),

       ('Erazmus z Hiszpanii', 'Jakiś nowy Erazmus jest dzisiaj w klubie. Dam ci dychę jak uda ci się go wyrwać!',
        'MEDIUM', 'RIZZ_FIGHT', 3, 'rizz_quest2.png'),
       ('Gruba ma problem', 'Ktoś zapytał się czy gruba pije i teraz trzeba ją ogarnąć. Załatw to!', 'MEDIUM',
        'STRENGTH_FIGHT', 1, 'fight_quest5.png'),
       ('Dresiarz robi młyn', 'Jakiś dresiarz robi awanturę na parkiecie. Będę wdzięczny jak postawisz go do pionu.',
        'MEDIUM', 'STRENGTH_FIGHT', 2, 'fight_quest2.png'),
       ('Zajmij barmankę', 'Mam do ciebie sprawę. Poderwij barmankę żeby ją czymś zająć, a ci się odwdzięczę!',
        'MEDIUM', 'RIZZ_FIGHT', 8, 'rizz_quest8.png'),
       ('Wkurzająca barmanka', 'Już dłużej nie wytrzymam z tą barmanką. Pokaż jej gdzie jest jej miejsce!', 'MEDIUM',
        'STRENGTH_FIGHT', 8, 'fight_quest9.png'),

       ('Pijany ochroniarz', 'Jeden z ochroniarzy chyba trochę za dużo wypił i zaczyna odwalać. Pójdziesz go ogarnąć?',
        'HARD', 'STRENGTH_FIGHT', 4, 'fight_quest4.png'),
       ('Poderwij blondynę', 'Widzisz tą blondynę przy stole? Stawiam moją dniówkę, że jej nie poderwiesz.', 'HARD',
        'RIZZ_FIGHT', 5, 'rizz_quest4.png'),
       ('Zrizzuj ochroniarza', 'Ja cie nie podpuszczam, ale...', 'HARD', 'RIZZ_FIGHT', 4, 'fight_quest4.png'),
       ('Wywal DJ-a z klubu', 'Wywal tego DJ-a z lokalu, już się nie da słuchać tego co on puszcza!', 'HARD',
        'STRENGTH_FIGHT', 7, 'fight_quest8.png'),


       ('Członek samorządu',
        'Studenci wydziału pracują nad pewnym niebezpiecznym dla rządu projektem. Trzeba go jakoś przekabacić, by im go uwalił i pozbyć się ich z uczelni. Dasz radę to zrobić?',
        'BOSS', 'RIZZ_FIGHT', (SELECT id FROM opponent_entity WHERE name = 'Andrzej Miękkowski'), ''),
       ('Psychol z polibudy',
        'Zwany także niekiedy "Bestią z Pieprzniczek", czyli miejscowości z której pochodzi. Absolutny szaleniec i zwyrol, ktoś musi się nim zająć. Zrobisz to?',
        'BOSS', 'STRENGTH_FIGHT', (SELECT id FROM opponent_entity WHERE name = 'Borys Piotrenko'), '');

INSERT INTO character_class_entity (class_name,
                                    base_endurance,
                                    base_rizz,
                                    base_strength,
                                    base_agility,
                                    base_luck,
                                    base_money)
VALUES ('Nerd', 30, 5, 5, 5, 30, 200),
       ('Erasmus', 35, 12, 5, 3, 5, 250),
       ('Dres', 45, 8, 10, 4, 1, 100);

INSERT INTO base_vehicle_entity (name,
                                 image_path,
                                 price,
                                 time_reduction_percent)
VALUES ('Rower składak', 'bicycle.png', 5, 10),
       ('Hulajnoga ksiajomi', 'scooter.png', 10, 15),
       ('Sejczento', 'sejczento.png', 20, 25),
       ('Olep asra', 'olep_asra.png', 50, 50),
       ('Bwm f67', 'bwm_f67.png', 100, 60),
       ('Traktor USRUS', 'tractor.png', 200, 90);

INSERT INTO user_entity(email, username, password, role)
VALUES ('admin@admin.pl', 'admin', '$2a$10$Tan2ga6Pji.v1tk3GP5p4O2dnDIAj7vitFJGGjPNrKy4q/DXg6aaW', 'ADMIN');