INSERT INTO base_item_entity (name,
                              item_type,
                              slot_type,
                              base_rizz,
                              base_strength,
                              base_agility,
                              base_endurance,
                              base_luck,
                              base_price,
                              image_path,
                              description
)
VALUES ('Zimowa czapka',        'EQUIPMENT', 'HEAD', 6, 3, 0, 9, 5, 40, 'item-winter-hat.png', 'Ma znajomy zapach.'),
       ('Słomiany kapelusz',    'EQUIPMENT', 'HEAD', 4, 0, 10, 8, 1, 40, 'item-straw-hat.png', ''),
       ('Różowe okulary',       'EQUIPMENT', 'HEAD', 8, 4, 3, 8, 8, 52, 'item-pink-sunglasses.png', ''),
       ('Czapka rolnika',       'EQUIPMENT', 'HEAD', 5, 4, 0, 11, 0, 35, 'item-farmer-cap.png', '50% rabatu na tygodnik rolniczy'),
       ('Pomarańczowe okulary', 'EQUIPMENT', 'HEAD', 6, 0, 4, 7, 3, 35, 'item-orange-sunglasses.png', 'Drobnym druczkiem ma napisane: "Made in PRL".'),
       ('Słuchawki gamingowe',  'EQUIPMENT', 'HEAD', 8, 0, 6, 6, 2, 42, 'item-gaming-headset.png', ''),
       ('Czerwona kominiara',   'EQUIPMENT', 'HEAD', 3, 7, 0, 12, 0, 40, 'item-balaclava.png', ''),
       ('Kask budowlańca',      'EQUIPMENT', 'HEAD', 2, 7, 0, 17, 0, 48, 'item-builder-helmet.png', 'Budowlaniec go raczej nie nosił, bo wygląda jak nowy.'),
       ('Czapka bucket',        'EQUIPMENT', 'HEAD', 5, 0, 4, 10, 2, 35, 'item-bucket-hat.png', ''),
       ('Okulary z wąsami',     'EQUIPMENT', 'HEAD', 11, 0, 0, 9, 10, 40, 'item-glasses-with-moustache.png', '+1000 do nierozpoznawalności'),

       ('Karta do akademika',       'EQUIPMENT', 'NECK', 4, 4, 0, 10, 0, 35, 'item-dormitory-card.png', 'Na odwrocie ma napisane "Pokój 509/1".'),
       ('Szalik Gajelonii',         'EQUIPMENT', 'NECK', 3, 8, 3, 6, 0, 40, 'item-sport-scarf.png', 'Lepiej nie pojawiać się z nim w złym mieście.'),
       ('Wisiorek z krucyfiksem',   'EQUIPMENT', 'NECK', 4, 4, 3, 5, 1, 40, 'item-crucifix-necklace.png', ''),
       ('Czerwone korale',          'EQUIPMENT', 'NECK', 5, 5, 4, 6, 2, 44, 'item-red-corals.png', ''),
       ('Złoty łańcuch',            'EQUIPMENT', 'NECK', 8, 6, 0, 5, 0, 40, 'item-golden-chain.png', 'Podobno oryginalnie kosztował 40 koła.'),
       ('Nieśmiertelnik',           'EQUIPMENT', 'NECK', 4, 4, 0, 15, 4, 55, 'item-dog-tag.png', 'Na wypadek gdybyś zaliczył/a zgona.'),
       ('Choker z kolcami',         'EQUIPMENT', 'NECK', 9, 2, 1, 5, 0, 50, 'item-choker.png', ''),
       ('Apaszka',                  'EQUIPMENT', 'NECK', 5, 0, 6, 4, 2, 45, 'item-scarf.png', ''),
       ('Krawat',                   'EQUIPMENT', 'NECK', 6, 3, 2, 5, 0, 45, 'item-tie.png', ''),
       ('Czerwona muszka',          'EQUIPMENT', 'NECK', 8, 0, 3, 8, 3, 52, 'item-bowtie.png', 'Po założeniu masz ochotę na herbatę z olbrzymią ilością cukru.'),

       ('Biała marynarka',      'EQUIPMENT', 'UPPER_BODY', 8, 4, 3, 14, 1, 48, 'item-white-suit.png', ''),
       ('Hawajska koszula',     'EQUIPMENT', 'UPPER_BODY', 7, 4, 5, 10, 1, 45, 'item-hawaiian-shirt.png', ''),
       ('Czarna suknia',        'EQUIPMENT', 'UPPER_BODY', 9, 0, 5, 12, 1, 44, 'item-black-dress.png', ''),
       ('Patriotyczna bluza',   'EQUIPMENT', 'UPPER_BODY', 0, 12, 6, 17, 0, 52, 'item-patriotic-hoodie.png', ''),
       ('Fartuch kuchenny',     'EQUIPMENT', 'UPPER_BODY', 9, 5, 8, 9, 4, 50, 'item-kitchen-apron.png', 'Przez żółądek do serca.'),
       ('Biała bluzka',         'EQUIPMENT', 'UPPER_BODY', 5, 2, 5, 14, 0, 45, 'item-white-blouse.png', ''),
       ('Skórzana kurtka',      'EQUIPMENT', 'UPPER_BODY', 8, 9, 0, 18, 1, 50, 'item-leather-jacket.png', ''),
       ('Długi płaszcz',        'EQUIPMENT', 'UPPER_BODY', 5, 11, 5, 17, 2, 65, 'item-long-jacket.png', 'Emanuje zapachem szlugów.'),
       ('Żonobijka',            'EQUIPMENT', 'UPPER_BODY', 8, 16, 3, 9, 0, 55, 'item-sleeveless-shirt.png', ''),
       ('Sztywna koszulka',     'EQUIPMENT', 'UPPER_BODY', 6, 13, 5, 14, 0, 40, 'item-rigid-tshirt.png', ''),

       ('Stare Jeansy',             'EQUIPMENT', 'LOWER_BODY', 4, 0, 2, 12, 0, 38, 'item-old-jeans.png', ''),
       ('Spodnie od garniaka',      'EQUIPMENT', 'LOWER_BODY', 7, 4, 4, 9, 1, 45, 'item-white-suit-pants.png', ''),
       ('Czarna spódniczka',        'EQUIPMENT', 'LOWER_BODY', 10, 0, 8, 10, 1, 47, 'item-black-skirt.png', ''),
       ('Spodnie moro',             'EQUIPMENT', 'LOWER_BODY', 3, 8, 3, 14, 0, 45, 'item-military-pants.png', ''),
       ('Fioletowe rajstopy',       'EQUIPMENT', 'LOWER_BODY', 6, 0, 7, 9, 1, 41, 'item-purple-tights.png', ''),
       ('Kąpielówki',               'EQUIPMENT', 'LOWER_BODY', 5, 3, 9, 9, 3, 44, 'item-swimming-trunks.png', ''),
       ('Ogrodniczki',              'EQUIPMENT', 'LOWER_BODY', 5, 6, 1, 13, 0, 40, 'item-dungarees.png', ''),
       ('Koszykarskie spodenki',    'EQUIPMENT', 'LOWER_BODY', 4, 5, 12, 11, 3, 52, 'item-basketball-shorts.png', ''),
       ('Spódnica baletnicy',       'EQUIPMENT', 'LOWER_BODY', 8, 4, 15, 6, 0, 48, 'item-ballerina-skirt.png', ''),
       ('Dresy Abibasa',            'EQUIPMENT', 'LOWER_BODY', 4, 7, 5, 13, 0, 50, 'item-sweatpants.png', ''),

       ('Wysokie buty',     'EQUIPMENT', 'FEET', 7, 7, 0, 11, 0, 44, 'item-high-soled-shoes.png', '+10 cm do wzrostu.'),
       ('Kalosze',          'EQUIPMENT', 'FEET', 3, 9, 1, 13, 0, 43, 'item-rain-boots.png', ''),
       ('Stare trampki',    'EQUIPMENT', 'FEET', 2, 6, 5, 8, 0, 32, 'item-old-sneakers.png', 'Powinny jeszcze wytrzymać z 10 lat.'),
       ('Crocsy',           'EQUIPMENT', 'FEET', 4, 9, 5, 12, 0, 50, 'item-crocs.png', ''),
       ('Sztyblety',        'EQUIPMENT', 'FEET', 6, 9, 1, 13, 0, 46, 'item-chelsea-boots.png', 'Rozlazłe, jakby chodził w nich jakiś steryd.'),
       ('Czarne szpilki',   'EQUIPMENT', 'FEET', 8, 7, 0, 8, 1, 40, 'item-black-heels.png', ''),
       ('Sandały',          'EQUIPMENT', 'FEET', 9, 4, 8, 7, 0, 47, 'item-sandals.png', 'Ze skarpetami w pakiecie stanowią zabójcze połączenie.'),
       ('Łyżwy',            'EQUIPMENT', 'FEET', 4, 4, 10, 11, 11, 55, 'item-skates.png', ''),
       ('Japonki',          'EQUIPMENT', 'FEET', 5, 2, 8, 7, 5, 43, 'item-flip-flops.png', ''),

       ('Złota branzoletka',        'EQUIPMENT', 'WRIST', 5, 6, 0, 5, 2, 40, 'item-golden-bracelet.png', ''),
       ('Sikor',                    'EQUIPMENT', 'WRIST', 8, 0, 0, 3, 3, 40, 'item-leather-watch.png', ''),
       ('Branzoletka przyjaźni',    'EQUIPMENT', 'WRIST', 5, 7, 0, 7, 1, 45, 'item-friendship-bracelet.png', ''),
       ('Frotkowa opaska',          'EQUIPMENT', 'WRIST', 5, 3, 0, 8, 7, 67, 'item-chill-wristband.png', '+10 do skręcania.'),
       ('Smartwatch',               'EQUIPMENT', 'WRIST', 4, 4, 4, 6, 4, 50, 'item-smartwatch.png', ''),
       ('Opaska policyjna',         'EQUIPMENT', 'WRIST', 7, 7, 3, 0, 1, 52, 'item-supervision-armband.png', 'Może zdążysz zrobić pare questów zanim po ciebie przyjadą.'),
       ('Zegarek szwagra',          'EQUIPMENT', 'WRIST', 9, 5, 0, 3, 0, 43, 'item-szwagier-watch.png', ''),
       ('Srebrna branzoleta',       'EQUIPMENT', 'WRIST', 6, 4, 1, 3, 0, 40, 'item-silver-bracelet.png', ''),
       ('Opaska odblaskowa',        'EQUIPMENT', 'WRIST', 4, 0, 3, 4, 0, 30, 'item-reflective-band.png', ''),
       ('Opaska z juwenaliów',      'EQUIPMENT', 'WRIST', 5, 2, 4, 6, 0, 80, 'item-juwenalia-wristband.png', 'Za rok będzie będzie 5 razy droższa, za te same statystyki.'),
       ('Opaska fluorescencyjna',   'EQUIPMENT', 'WRIST', 6, 0, 7, 0, 3, 35, 'item-fluorescent-wristband.png', ''),
       ('Cukierkowy zegarek',       'EQUIPMENT', 'WRIST', 8, 5, 0, 0, 5, 45, 'item-candy-watch.png', 'Pilnuj, żeby nikt ci go nie zjadł.'),

       ('Zapalniczka',      'EQUIPMENT', 'EMBLEM', 7, 5, 3, 0, 3, 45, 'item-lighter.png', 'Ledwo działa, ale fajnie wygląda.'),
       ('Paczka szlugów',   'EQUIPMENT', 'EMBLEM', 10, 7, 0, 0, 4, 50, 'item-cigarettes.png', 'Z ruską banderolą.'),
       ('Tani vape',        'EQUIPMENT', 'EMBLEM', 6, 7, 0, 0, 2, 40, 'item-cheap-vape.png', 'Skasowany jakiemuś uczniowi podstawówki.'),
       ('Pluszak Babulu',   'EQUIPMENT', 'EMBLEM', 7, 4, 1, 0, 5, 55, 'item-babulu-plush.png', ''),
       ('Dezodorant',       'EQUIPMENT', 'EMBLEM', 8, 8, 3, 3, 0, 48, 'item-deodorant.png', 'Idealny na cygański prysznic.'),
       ('Pudełko snusów',   'EQUIPMENT', 'EMBLEM', 7, 6, 1, 3, 2, 48, 'item-snus.png', ''),
       ('Różowa torebka',   'EQUIPMENT', 'EMBLEM', 6, 9, 2, 4, 5, 52, 'item-pink-bag.png', ''),
       ('Karty tarota',     'EQUIPMENT', 'EMBLEM', 5, 5, 5, 7, 12, 65, 'item-tarot.png', ''),
       ('Butelka zwrotna',  'EQUIPMENT', 'EMBLEM', 6, 9, 0, 4, 3, 51, 'item-returnable-bottle.png', 'Jeszcze takie trzy i będzie kolejne piwo.'),
       ('Alkomat',          'EQUIPMENT', 'EMBLEM', 5, 5, 7, 0, 5, 40, 'item-alkomat.png', ''),
       ('Konsola',          'EQUIPMENT', 'EMBLEM', 6, 7, 0, 0, 10, 55, 'item-console.png', ''),


       ('Numerek do szatni 03',     'ITEM_TOKEN', 'NONE', 0, 0, 0, 0, 1, 0, 'item-token-03.png', 'Wymień go u szatniarza.'),
       ('Numerek do szatni 12',     'ITEM_TOKEN', 'NONE', 0, 0, 0, 0, 1, 0, 'item-token-12.png', 'Wymień go u szatniarza.'),
       ('Numerek do szatni 13',     'ITEM_TOKEN', 'NONE', 0, 0, 0, 0, 1, 0, 'item-token-13.png', 'Wymień go u szatniarza.'),
       ('Numerek do szatni 21',     'ITEM_TOKEN', 'NONE', 0, 0, 0, 0, 1, 0, 'item-token-21.png', 'Wymień go u szatniarza.'),
       ('Numerek do szatni 34',     'ITEM_TOKEN', 'NONE', 0, 0, 0, 0, 1, 0, 'item-token-34.png', 'Wymień go u szatniarza.'),
       ('Numerek do szatni 55',     'ITEM_TOKEN', 'NONE', 0, 0, 0, 0, 1, 0, 'item-token-55.png', 'Wymień go u szatniarza.'),
       ('Numerek do szatni 58',     'ITEM_TOKEN', 'NONE', 0, 0, 0, 0, 1, 0, 'item-token-58.png', 'Wymień go u szatniarza.'),
       ('Numerek do szatni 67',     'ITEM_TOKEN', 'NONE', 0, 0, 0, 0, 7, 0,'item-token-67.png', 'Wymień go u szatniarza.'),
       ('Numerek do szatni 77',     'ITEM_TOKEN', 'NONE', 0, 0, 0, 0, 1, 0, 'item-token-77.png', 'Wymień go u szatniarza.'),
       ('Numerek do szatni 89',     'ITEM_TOKEN', 'NONE', 0, 0, 0, 0, 1, 0, 'item-token-89.png', 'Wymień go u szatniarza.'),
       ('Numerek do szatni 99',     'ITEM_TOKEN', 'NONE', 0, 0, 0, 0, 1, 0, 'item-token-99.png', 'Wymień go u szatniarza.'),
       ('Numerek do szatni 420',    'ITEM_TOKEN', 'NONE', 0, 0, 0, 0, 7, 0,'item-token-420.png', 'Wymień go u szatniarza.');

INSERT INTO opponent_entity (name,
                             base_rizz,
                             base_strength,
                             base_agility,
                             base_endurance,
                             base_luck,
                             image_path)
VALUES ('Gruba', 3, 6, 1, 43, 1, 'opponent_gruba.png'),
       ('Dresiarz', 5, 8, 5, 36, 2, 'opponent_dresiarz.png'),
       ('Hiszpan', 9, 6, 7, 29, 2, 'opponent_hiszpan.png'),
       ('Ochroniarz', 6, 10, 6, 48, 7, 'opponent_ochroniarz.png'),
       ('Blondyna', 13, 6, 8, 27, 3, 'opponent_blondyna.png'),
       ('Menel', 4, 5, 3, 31, 10, 'opponent_menel.png'),
       ('DJ', 10, 7, 5, 41, 4, 'opponent_dj.png'),
       ('Barmanka', 8, 6, 6, 33, 4, 'opponent_bartender.png'),


       ('Andrzej Miękkowski', 50, 0, 5, 500, 5, 'boss_andrzej.png'),
       ('Borys Piotrenko', 0, 80, 10, 1000, 30, 'boss_piotrenko.png');



INSERT INTO quest_entity (title,
                          description,
                          quest_tier,
                          quest_type,
                          opponent_id,
                          image_path)
VALUES ('Rizzowanie grubej', 'Wydajesz się być zdesperowany. Spróbuj może zrizzować grubą.', 'EASY', 'RIZZ_FIGHT', 1, 'rizz_quest1.png'),
       ('Wyjaśnij Hiszpana', 'Wkurza mnie już ten Erazmus, pokaż mu gdzie jego miejsce!', 'EASY', 'STRENGTH_FIGHT', 3, 'fight_quest6.png'),
       ('Pozbądź się menela', 'Jakiś menel wtargnął nam do lokalu. Pozbędziesz się go?', 'EASY', 'STRENGTH_FIGHT', 6,'fight_quest7.png'),
       ('Ogarnij DJ-a', 'Przemów do rozsądku temu DJ-owi, żeby puścił coś normalnego.', 'EASY', 'STRENGTH_FIGHT', 7,'fight_quest8.png'),
       ('Samotny menel', 'Szkoda mi się zrobiło tego menela, weź idź z nim zatańcz czy coś.', 'EASY', 'RIZZ_FIGHT', 6, 'rizz_quest7.png'),
       ('Poderwij dresiarza', 'Widzisz tego dresa na parkiecie? Założę się że go nie poderwiesz!', 'EASY', 'RIZZ_FIGHT', 2, 'rizz_quest4.png'),
       ('Zajmij barmankę', 'Mam do ciebie sprawę. Weź na parkiet barmankę żeby ją czymś zająć, odwdzięczę się!', 'EASY', 'RIZZ_FIGHT', 8, 'rizz_quest8.png'),

       ('Erazmus z Hiszpanii', 'Jakiś nowy Erazmus jest dzisiaj w klubie. Dam ci dychę jak uda ci się go wyrwać!', 'MEDIUM', 'RIZZ_FIGHT', 3, 'rizz_quest2.png'),
       ('Gruba ma problem', 'Ktoś zapytał się czy gruba pije i teraz trzeba ją ogarnąć. Załatw to!', 'MEDIUM','STRENGTH_FIGHT', 1, 'fight_quest5.png'),
       ('Dresiarz robi młyn', 'Jakiś dresiarz robi awanturę na parkiecie. Będę wdzięczny jak postawisz go do pionu.', 'MEDIUM', 'STRENGTH_FIGHT', 2, 'fight_quest2.png'),
       ('Poderwij barmankę', 'Jak poderwiesz barmankę postawię ci browara. Może nawet dwa.', 'MEDIUM', 'RIZZ_FIGHT', 8, 'rizz_quest8.png'),
       ('Wkurzająca barmanka', 'Już dłużej nie wytrzymam z tą barmanką. Pokaż jej gdzie jest jej miejsce!', 'MEDIUM', 'STRENGTH_FIGHT', 8, 'fight_quest9.png'),
       ('Poderwij DJ-a', 'Weź tego DJ-a na parkiet, to może chociaż przez chwilę poleci coś normalnego.', 'MEDIUM', 'RIZZ_FIGHT', 7, 'rizz_quest10.png'),

       ('Pijany ochroniarz', 'Jeden z ochroniarzy chyba trochę za dużo wypił i zaczyna odwalać. Pójdziesz go ogarnąć?', 'HARD', 'STRENGTH_FIGHT', 4, 'fight_quest4.png'),
       ('Poderwij blondynę', 'Widzisz tą blondynę przy stole? Stawiam moją dniówkę, że jej nie poderwiesz.', 'HARD', 'RIZZ_FIGHT', 5, 'rizz_quest4.png'),
       ('Zrizzuj ochroniarza', 'Ja cie nie podpuszczam, ale...', 'HARD', 'RIZZ_FIGHT', 4, 'rizz_quest9.png'),
       ('Wywal DJ-a z klubu', 'Wywal tego DJ-a z lokalu, już się nie da słuchać tego co on puszcza!', 'HARD', 'STRENGTH_FIGHT', 7, 'fight_quest8.png'),
       ('Wywalić dresiarza', 'Ten dresiarz rzuca się do wszystkich, wyrzuć go z lokalu', 'HARD', 'STRENGTH_FIGHT', 2, 'fight_quest2.png'),


       ('Członek samorządu', 'Studenci wydziału pracują nad pewnym niebezpiecznym dla rządu projektem. Trzeba go jakoś przekabacić, by im go uwalił i pozbyć się ich z uczelni. Dasz radę to zrobić?','BOSS', 'RIZZ_FIGHT', (SELECT id FROM opponent_entity WHERE name = 'Andrzej Miękkowski'), ''),
       ('Psychol z polibudy','Zwany także niekiedy "Bestią z Pieprzniczek", czyli miejscowości z której pochodzi. Absolutny szaleniec i zwyrol, ktoś musi się nim zająć. Zrobisz to?', 'BOSS', 'STRENGTH_FIGHT', (SELECT id FROM opponent_entity WHERE name = 'Borys Piotrenko'), '');

INSERT INTO character_class_entity (class_name,
                                    base_endurance,
                                    base_rizz,
                                    base_strength,
                                    base_agility,
                                    base_luck,
                                    base_money)
VALUES ('Nerd', 40, 5, 5, 7, 33, 300),
       ('Erasmus', 45, 13, 7, 10, 5, 250),
       ('Dres', 50, 8, 12, 10, 1, 200);

INSERT INTO base_vehicle_entity (name,
                                 image_path,
                                 price,
                                 time_reduction_percent)
VALUES ('Rower składak', 'bicycle.png', 5, 10),
       ('Hulajnoga ksiajomi', 'scooter.png', 10, 15),
       ('Sejczento', 'sejczento.png', 20, 25),
       ('Olep asra', 'olep_asra.png', 50, 50),
       ('Bwm f67', 'bwm_f67.png', 100, 60),
       ('Traktor USRUS', 'tractor.png', 200, 90);
