spring.application.name=SFGSpringProjekt

spring.datasource.url=jdbc:mysql://localhost:3306/Game?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=game_app_user
spring.datasource.password=JeszczeBardziejKochamSystemyBazDanych123$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.user=game_admin_user
spring.flyway.password=KochamWymyslacHaslaUzytkownikowPoNocach123$

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs