INSERT INTO base_item_entity (name,
                              description,
                              slot_type,
                              base_rizz,
                              base_strength,
                              base_agility,
                              base_endurance,
                              base_luck,
                              base_price,
                              image_path)
VALUES
    ('Zimowa czapka', 'opis', 'HEAD', 5, 2, 6, 2, 8, 20, 'item-winter-hat.png'),
    ('Zapalniczka', 'opis', 'EMBLEM', 6, 5, 3, 1, 7, 25, 'item-lighter.png'),
    ('Stare Jeansy', 'opis', 'LOWER_BODY', 3, 2, 2, 7, 1, 18, 'item-old-jeans.png'),
    ('Hawajska koszula', 'opis', 'UPPER_BODY', 6, 3, 5, 3, 6, 25, 'item-hawaiian-shirt.png'),
    ('Wisiorek z krucyfiksem', 'opis', 'NECK', 3, 3, 2, 5, 7, 20, 'item-crucifix-necklace.png'),
    ('Sztyblety', 'opis', 'FEET', 5, 4, 2, 5, 2, 26, 'item-chelsea-boots.png'),
    ('Sikor', 'opis', 'WRIST', 7, 3, 2, 3, 3, 20, 'item-leather-watch.png'),
    ('Paczka szlugow', 'opis', 'EMBLEM', 9, 6, 1, 3, 5, 30, 'item-cigarettes.png'),
    ('Karta do akademika', 'opis', 'NECK', 6, 3, 3, 3, 2, 15, 'item-dormitory-card.png'),
    ('Szalik Gajelonii', 'opis', 'NECK', 2, 6, 4, 4, 1, 16, 'item-sport-scarf.png'),
    ('Pomaranczowe okulary', 'opis', 'HEAD', 6, 2, 4, 2, 6, 15, 'item-orange-sunglasses.png'),
    ('Spodnie od garniaku', 'opis', 'LOWER_BODY', 7, 4, 3, 4, 2, 25, 'item-white-suit-pants.png'),
    ('Biala marynarka', 'opis', 'UPPER_BODY', 8, 4, 3, 6, 2, 28, 'item-white-suit.png'),
    ('Stare trampki', 'opis', 'FEET', 2, 4, 5, 4, 2, 12, 'item-old-sneakers.png'),
    ('Crocsy', 'opis', 'FEET', 5, 5, 5, 5, 3, 22, 'item-crocs.png'),
    ('Czapka rolnika', 'opis', 'HEAD', 4, 2, 4, 5, 2, 15, 'item-farmer-cap.png'),
    ('Tani vape', 'opis', 'EMBLEM', 6, 5, 2, 1, 4, 20, 'item-cheap-vape.png'),
    ('Branzoletka przyjazni', 'opis', 'WRIST', 6, 2, 3, 7, 5, 25, 'item-friendship-bracelet.png'),
    ('Pluszak Babulu', 'opis', 'EMBLEM', 6, 3, 5, 1, 7, 35, 'item-babulu-plush.png'),
    ('Dezodorant', 'opis', 'EMBLEM', 7, 6, 4, 1, 2, 20, 'item-deodorant.png'),
    ('Pudelko snusow', 'opis', 'EMBLEM', 5, 4, 4, 3, 5, 28, 'item-snus.png'),
    ('Czarna suknia', 'opis', 'UPPER_BODY', 8, 4, 4, 6, 4, 24, 'item-black-dress.png'),
    ('Patriotyczna bluza', 'opis', 'UPPER_BODY', 3, 10, 6, 8, 1, 30, 'item-patriotic-hoodie.png'),
    ('Rozowa torebka', 'opis', 'EMBLEM', 6, 9, 5, 2, 5, 28, 'item-pink-bag.png'),
    ('Czarne szpilki', 'opis', 'FEET', 8, 4, 1, 3, 3, 20, 'item-black-heels.png'),
    ('Czarna spodniczka', 'opis', 'LOWER_BODY', 7, 4, 6, 5, 3, 27, 'item-black-skirt.png'),
    ('Zlota branzoletka', 'opis', 'WRIST', 4, 5, 3, 2, 8, 20, 'item-golden-bracelet.png'),
    ('Wysokie buty', 'opis', 'FEET', 3, 7, 1, 5, 1, 24, 'item-high-soled-shoes.png'),
    ('Fartuch kuchenny', 'opis', 'UPPER_BODY', 7, 4, 8, 2, 7, 30, 'item-kitchen-apron.png'),
    ('Rozowe okulary', 'opis', 'HEAD', 8, 3, 6, 2, 9, 32, 'item-pink-sunglasses.png'),
    ('Kalosze', 'opis', 'FEET', 2, 5, 4, 8, 2, 23, 'item-rain-boots.png'),
    ('Czerwone korale', 'opis', 'NECK', 5, 5, 5, 1, 6, 24, 'item-red-corals.png'),
    ('Slomiany kapelusz', 'opis', 'HEAD', 4, 4, 9, 4, 5, 20, 'item-straw-hat.png'),
    ('Karty tarota', 'opis', 'EMBLEM', 4, 4, 4, 4, 14, 40, 'item-tarot.png'),
    ('Biala bluzka', 'opis', 'UPPER_BODY', 5, 6, 8, 5, 2, 25, 'item-white-blouse.png'),
    ('Skorzana kurtka', 'opis', 'UPPER_BODY', 7, 5, 1, 5, 2, 22, 'item-leather-jacket.png');